# Soru setini derlemek için yardımcı betik: kısa bir tablodan data/questions.json üretir.
# Yeni soru eklemek için JSON'u elle de düzenleyebilirsiniz.
import json
Q = [
("concession-clause","The committee declined to revise the regulation ____ it had received numerous complaints.",
 ["despite","in spite of","even though","because of","therefore"],2,
 "Boşluktan sonra tam cümle (it had received ...) var ve zıtlık anlamı isteniyor. Despite / In spite of isim alır; Even though tam cümle alır."),
("concession-noun","____ the unfavourable weather conditions, the expedition reached the summit on schedule.",
 ["Although","Despite","Even though","Whereas","However"],1,
 "Boşluktan sonra isim grubu (the unfavourable weather conditions) geliyor. Zıtlık + isim = Despite."),
("contrast-clause","Some analysts believe the recovery will be rapid, ____ others expect a prolonged slowdown.",
 ["because","unless","whereas","despite","so that"],2,
 "Cümlenin iki yarısı birbirine zıt görüşler içeriyor ve ikinci yarıda tam cümle var: Whereas ('oysa')."),
("adv-contrast","The new drug has proven effective in trials; ____, it is not yet available to patients because of licensing delays.",
 ["because","however","although","in case","so that"],1,
 "Noktalı virgülden sonra virgülle ayrılmış, zıtlık bildiren bir zarf gerekiyor: However. Although, noktalı virgülden sonra iki cümleyi bağlayamaz."),
("contrast-adv","Exports of manufactured goods have grown steadily; ____, agricultural exports have fallen sharply.",
 ["likewise","therefore","moreover","on the other hand","in other words"],3,
 "İki zıt bilgi (artış – düşüş) karşılaştırılıyor: On the other hand."),
("unlike","____ most of his colleagues, Dr. Aydın rejected the proposed theory.",
 ["Despite","Unlike","Because of","Instead","Whereas"],1,
 "Kişiler arasında zıtlık ve sonrasında isim grubu var: Unlike. Whereas tam cümle gerektirir."),
("cause-clause","____ the bridge was structurally unsafe, the authorities closed it to traffic.",
 ["Because of","Despite","Since","Unless","Whereas"],2,
 "Boşluktan sonra tam cümle ve neden anlamı var. Because of isim alır; Since tam cümle alır."),
("cause-noun","The flight was cancelled ____ the dense fog that covered the entire region.",
 ["because","although","owing to","so that","while"],2,
 "Boşluktan sonra isim grubu (the dense fog ...) var: Owing to. Because ve although tam cümle ister."),
("cause-given","____ the funding has finally been approved, the researchers can begin the second phase.",
 ["Unless","Now that","Even if","Whereas","Lest"],1,
 "Gerçekleşmiş bir durumdan yola çıkarak sonuç bildiriliyor: Now that ('madem ki')."),
("result-adv","The factory failed to meet safety standards; ____, it was ordered to suspend production.",
 ["nevertheless","in contrast","consequently","besides","although"],2,
 "İkinci cümle birincinin sonucunu bildiriyor: Consequently."),
("so-that-degree","The instructions were ____ ambiguous that most participants misinterpreted them.",
 ["such","too","so","very","enough"],2,
 "'ambiguous' sıfatı tek başına duruyor ve 'that' ile sonuç cümlesi geliyor: so ... that."),
("such-that","It was ____ a challenging task that only a few candidates managed to complete it.",
 ["so","such","too","enough","very"],1,
 "'a challenging task' isim grubu olduğu için such + a + sıfat + isim + that kullanılır."),
("purpose-clause","The researchers anonymised the data ____ participants' privacy would be protected.",
 ["so as to","in order to","so that","lest","despite"],2,
 "Yeni özne (participants' privacy) ve modal (would) var: so that. In order to / so as to sonrasında yalın fiil gelir."),
("purpose-inf","Several countries have imposed stricter regulations ____ reduce carbon emissions.",
 ["so that","in order to","in order that","because","lest"],1,
 "Sonrasında yalın fiil (reduce) var ve özne değişmiyor: in order to + V1."),
("lest","He kept the documents locked in a safe lest they ____ stolen.",
 ["will be","would be","should be","are","were not"],2,
 "Lest + should + V1 (veya yalın fiil). Lest zaten olumsuz anlam taşır; 'not' kullanılmaz."),
("in-case","Take a spare key with you ____ you lose the first one.",
 ["unless","in case","although","in case of","as long as"],1,
 "Önlem anlamı var ve sonrasında tam cümle geliyor: in case. 'In case of' isim alır."),
("condition-strict","Visitors are permitted to take photographs ____ they do not use a flash.",
 ["unless","provided that","even if","in case","whereas"],1,
 "'Sadece flaş kullanmamaları şartıyla' anlamı isteniyor: provided that."),
("unless","The negotiations will collapse ____ both parties make concessions.",
 ["unless","provided that","as long as","in case","so that"],0,
 "'Her iki taraf taviz vermedikçe' anlamı için unless gerekir (unless = if not)."),
("even-if","____ the treatment proves effective, patients will need regular check-ups for several years.",
 ["Despite","Even if","Unless","Whereas","Because of"],1,
 "Henüz kesin olmayan bir olasılık söz konusu ve tam cümle var: Even if."),
("inverted-conditionals","____ the government acted earlier, the crisis might have been prevented.",
 ["Have","Had","Were","Should","Unless"],1,
 "Ana cümlede might have been prevented (3. tip koşul) var. If'siz devrik yapı: Had + özne + V3."),
("but-for","____ the volunteers' tireless efforts, the festival could not have taken place.",
 ["Unless","But for","Although","Because","While"],1,
 "Sonrasında isim grubu var ve anlam 'olmasaydı': But for (= if it had not been for)."),
("otherwise","You must register before the deadline; ____, you will lose your right to apply.",
 ["moreover","therefore","otherwise","however","besides"],2,
 "Önceki cümlede zorunluluk var, ikinci cümle olumsuz sonuç bildiriyor: otherwise."),
("addition-adv","The new policy will lower administrative costs; ____, it will make the process more transparent.",
 ["nevertheless","on the other hand","furthermore","otherwise","consequently"],2,
 "İkinci cümle aynı yönde ek bir olumlu bilgi ekliyor: furthermore."),
("addition-noun","____ offering free tuition, the university provides accommodation for gifted students.",
 ["Despite","In addition to","Instead of","Because of","In spite of"],1,
 "Sonrasında V-ing var ve anlam 'ek olarak': In addition to."),
("not-only","Not only ____ the company lose its largest client, but it also had to lay off hundreds of workers.",
 ["it did","did","was","has","is"],1,
 "Not only cümle başındayken devrik yapı gerekir: Not only did the company lose ..."),
("both-and","Both the manager ____ the assistant were present at the meeting.",
 ["or","nor","and","as well","but"],2,
 "Both yalnızca and ile eşleşir."),
("either-neither","Neither the director nor the employees ____ aware of the changes.",
 ["was","is","were","has been","being"],2,
 "Neither ... nor yapısında fiil, nor'a yakın özneye uyar: the employees → were."),
("time-while","____ the delegates were discussing the proposal, a fire alarm went off.",
 ["During","While","Despite","Since","Whereas"],1,
 "Sonrasında tam cümle (past continuous) var ve eş zamanlılık anlatılıyor: While. During isim alır."),
("time-as-soon","As soon as the new system ____ installed, the staff will receive training.",
 ["will be","would be","is","was","being"],2,
 "Zaman bağlaçlarından sonra gelecek için present simple kullanılır: is installed."),
("time-until","The committee did not announce its decision ____ all the evidence had been reviewed.",
 ["while","until","since","although","by"],1,
 "'Not ... until' kalıbı: kanıtlar gözden geçirilene kadar karar açıklanmadı."),
("time-by-the-time","By the time the ambulance arrived, the patient ____ consciousness.",
 ["loses","lost","had lost","will lose","has lost"],2,
 "By the time + past simple → ana cümlede past perfect (had lost)."),
("time-whenever","____ the economy slows down, unemployment tends to rise.",
 ["Whenever","Although","Unless","Whereas","So that"],0,
 "Genelleme ve tekrar eden durum anlatılıyor: Whenever."),
("time-since","Inflation ____ steadily since the central bank changed its policy last year.",
 ["rises","rose","has been rising","is rising","will rise"],2,
 "Since + past simple olduğu için ana cümlede present perfect (continuous) gerekir."),
("time-hardly","Hardly had the speaker finished ____ the audience burst into applause.",
 ["than","when","while","as if","until"],1,
 "Hardly / Scarcely ... WHEN; No sooner ... THAN."),
("time-before","____ launching the product, the company carried out extensive market research.",
 ["Prior to","Despite","Because","Unless","Whereas"],0,
 "Sonrasında V-ing var ve zaman önceliği anlatılıyor: Prior to."),
("time-after","____ the earthquake, thousands of residents were left homeless.",
 ["Following","Prior to","Unless","Whereas","Lest"],0,
 "Sonrasında isim grubu var ve olayın ardından anlamı isteniyor: Following."),
("time-during","Many historic buildings were damaged ____ the war.",
 ["while","during","since","as","although"],1,
 "Sonrasında isim (the war) var: during."),
("instead-of","Many students prefer studying at home ____ going to the library.",
 ["instead","rather","instead of","in spite of","because of"],2,
 "Sonrasında V-ing var ve tercih anlamı isteniyor: instead of."),
("except","All the applicants ____ one were invited to the interview.",
 ["except","despite","unless","instead of","whereas"],0,
 "'Biri hariç' anlamı için except gerekir."),
("whatever-however","____ hard he tried, he could not solve the problem.",
 ["Whatever","However","Whoever","Whenever","Wherever"],1,
 "However + sıfat / zarf + özne + fiil: 'Ne kadar uğraşsa da'."),
("whether","____ the project succeeds or not, the team will receive a bonus.",
 ["If","Unless","Whether","Because","Lest"],2,
 "'İster ... ister' anlamı için whether ... or (not) kullanılır."),
("as-if","She behaves as if she ____ the owner of the company.",
 ["is","has been","were","will be","being"],2,
 "Gerçek dışı karşılaştırmada as if + were (şimdiki zaman)."),
("according-to","____ the latest report, the number of tourists increased by 12 per cent.",
 ["Regarding","According to","Owing to","Instead of","Despite"],1,
 "Bir kaynağa dayanarak bilgi veriliyor: According to."),
("regarding","____ the question of funding, no decision has been made yet.",
 ["Despite","Unlike","With regard to","Because of","Instead of"],2,
 "Konuyu belirten ifade: With regard to (-e ilişkin)."),
("similarly","The first treatment reduced symptoms in most patients; ____, the second proved equally effective.",
 ["however","similarly","otherwise","consequently","on the contrary"],1,
 "İki cümle benzer yönde olduğu için Similarly gerekir."),
("for-example","Several industries, ____ textiles and steel, were severely affected.",
 ["such as","as a result","in contrast","otherwise","whereas"],0,
 "Örnek verirken isim grubundan önce such as kullanılır."),
("in-other-words","The company aims to be carbon-neutral by 2035; ____, it will eliminate all net emissions within a decade.",
 ["otherwise","in other words","however","nevertheless","despite"],1,
 "İkinci cümle birincinin yeniden ifadesi: In other words."),
("in-conclusion","____, the evidence suggests that early intervention is far more cost-effective.",
 ["In conclusion","Moreover","Nevertheless","For example","Meanwhile"],0,
 "Metnin genel çıkarımı ve sonucu: In conclusion."),
("in-fact","Many assumed the project would fail; ____, it exceeded every expectation.",
 ["in fact","in case","unless","lest","whereas"],0,
 "Önceki yanlış varsayımı düzeltiyor: In fact."),
("meanwhile","The engineers repaired the generator. ____, the technicians restored power to the east wing.",
 ["Meanwhile","Otherwise","Whereas","Unless","Because"],0,
 "İki olay aynı anda gerçekleşiyor: Meanwhile."),
("afterwards","The patients were examined first; ____, they were referred to specialists.",
 ["Subsequently","Whereas","Despite","Lest","Owing to"],0,
 "Olaylar kronolojik sıradadır: Subsequently."),
("result-so","The pipeline burst during the night, ____ the entire district was left without water.",
 ["because","although","so","unless","whereas"],2,
 "İkinci cümle birincinin sonucu ve araya virgül giriyor: so ('bu yüzden')."),
("as-a-result-of","____ the merger, more than 2,000 employees lost their jobs.",
 ["As a result","As a result of","Despite","Unless","Whereas"],1,
 "Sonrasında isim grubu (the merger) var: As a result of. 'As a result' tek başına cümleler arasında kullanılır."),
("by-means-of","The data were collected ____ structured interviews.",
 ["by means of","in spite of","instead","unless","whereas"],0,
 "Yöntem / araç belirten ve isim alan ifade: by means of."),
("but","The proposal was innovative, ____ it was too expensive to implement.",
 ["so","but","because","unless","therefore"],1,
 "Virgülden sonra zıt bir bilgi geliyor: but."),
("unlike","The study focused on long-term outcomes ____ short-term gains.",
 ["as opposed to","because of","provided that","in case","so that"],0,
 "İki isim grubu karşıtlık içinde: as opposed to."),
("regardless-of","Admission is based on merit, ____ an applicant's background.",
 ["regardless of","in case of","such as","so that","otherwise"],0,
 "'Geçmişine bakılmaksızın' anlamı için regardless of gerekir."),
("as-as","The new model is as reliable ____ the older one.",
 ["than","as","like","that","so"],1,
 "Eşitlik kalıbı: as + sıfat + as."),
("just-as","Just as technology has transformed communication, so ____ it reshaped education.",
 ["it has","has it","is it","does it","it is"],1,
 "Just as ... so yapısında so'dan sonra devrik yapı gelir: so has it reshaped."),
("if-basic","If the government ____ interest rates, borrowing will become more expensive.",
 ["will raise","raised","raises","would raise","had raised"],2,
 "Ana cümlede will var (1. tip koşul): if + present simple."),
("time-upon","____ at the airport, the delegation was welcomed by the minister.",
 ["Upon arriving","Upon arrived","Upon to arrive","Upon arrive","After arrive"],0,
 "Upon / On + V-ing = varır varmaz."),
("in-terms-of","____ cost, the second option is clearly preferable.",
 ["In terms of","Because","Although","Whereas","Unless"],0,
 "Sonrasında isim var ve 'açısından' anlamı isteniyor: In terms of."),
("along-with","The director, along with his deputies, ____ invited to the ceremony.",
 ["were","are","was","have been","have"],2,
 "Along with araya girse de özne tekil (the director) olduğu için fiil tekil: was."),
("by-ving","The firm reduced its costs ____ part of its production.",
 ["by outsource","by outsourcing","in order outsourcing","for outsource","to outsourcing"],1,
 "Yöntem anlatırken by + V-ing kullanılır."),
("instead-adv","The council rejected the plan to widen the road. ____, it proposed building a new tram line.",
 ["Instead","Instead of","Although","Unless","Because"],0,
 "Cümle başında tek başına gelen zarf: Instead. Instead of isim / V-ing ister."),
]
out=[]
for i,(cid,stem,opts,ans,exp) in enumerate(Q,1):
    out.append({"id":f"q{i:03d}","cardIds":[cid],"stem":stem,"options":opts,"answer":ans,"explanation":exp})
json.dump(out,open("data/questions.json","w",encoding="utf-8"),ensure_ascii=False,indent=2)
print(len(out))
