# Tuzak tipi sorular: çeldiricileri birbirine benzeyen bağlaçlardan seçilmiş sorular.
# Her satır: (kart id, soru, şıklar, doğru şık indeksi, tuzak açıklaması)
import json
T = [
("concession-clause","____ the new regulations were widely criticised, the government refused to amend them.",["Despite","Even though","However","In spite of","Nevertheless"],1,"Boşluktan sonra tam cümle var. Despite / In spite of isim ister; However / Nevertheless ise cümleler arası zarftır, cümle başında bağlaç görevi görmez."),
("concession-clause","The hotel was expensive. The service, ____, was poor.",["though","although","even though","despite","because"],0,"Though cümle ortasında / sonunda virgülle zarf olarak 'ama, yine de' anlamı taşır; although ve even though bu konumda kullanılmaz."),
("concession-noun","____ the fact that the experiment had failed twice, the team decided to repeat it.",["Despite","Although","Even though","However","Whereas"],0,"'Despite the fact that + tam cümle' kalıbı vardır. Although / Even though 'the fact that' ile birlikte kullanılmaz."),
("concession-noun","____ having studied for months, he failed the exam.",["Although","In spite of","Even though","However","Nevertheless"],1,"Sonrasında V-ing var. Edat olan In spite of / Despite V-ing alır; Although / Even though tam cümle ister."),
("contrast-clause","The first group of students performed well, ____ the second group did poorly.",["whereas","during","despite","owing to","instead of"],0,"Whereas tam cümle alır. During, despite, owing to ve instead of isim ister."),
("contrast-clause","Sales of electric cars rose sharply last year; ____, sales of petrol cars fell.",["whereas","while","on the other hand","although","because"],2,"Noktalı virgülden sonra bağlaç (whereas, while, although) gelmez; cümleler arası zarf (on the other hand) gerekir."),
("adv-contrast","The weather was terrible. ____, the match went ahead as planned.",["Although","Nevertheless","Despite","In spite of","Because"],1,"Önceki cümle noktayla bitiyor; yeni cümleyi başlatan zıtlık zarfı gerekir. Although tek başına cümle başlatamaz, Despite / In spite of isim ister."),
("adv-contrast","She was exhausted, ____ she kept working until midnight.",["however","nevertheless","yet","although","therefore"],2,"Virgülle iki cümleyi bağlamak için bağlaç gerekir. However / Nevertheless zarftır, therefore sonuç bildirir; yet eş değerli bağlaçtır."),
("contrast-adv","Some experts predict inflation will fall; ____, others warn it will rise further.",["on the other hand","furthermore","therefore","for instance","similarly"],0,"İki zıt görüş karşılaştırılıyor. Furthermore ve similarly aynı yönde bilgi ekler."),
("contrast-adv","On the one hand, remote work saves commuting time; on the ____ hand, it can lead to isolation.",["another","other","second","next","contrary"],1,"'On the one hand ... on the other hand' ikilisi sabit bir kalıptır."),
("unlike","____ the climate in Spain, the climate in England is cool and wet.",["Unlike","Whereas","Although","However","Despite"],0,"Unlike isim alır. Whereas / Although tam cümle ister, However cümleler arası zarftır, Despite zıtlık değil taviz bildirir."),
("unlike","The new policy, ____ the previous one, focuses on prevention.",["in contrast to","in contrast","however","whereas","although"],0,"In contrast to + isim; 'in contrast' ise tek başına cümle başında / arasında zarf olarak kullanılır."),
("cause-clause","____ the road was icy, many drivers decided to stay at home.",["Because of","Since","Despite","Owing to","In spite of"],1,"Sonrasında tam cümle var. Because of / Owing to isim ister; Despite / In spite of zıtlık bildirir."),
("cause-clause","The match was postponed ____ the heavy rain.",["because","since","as","because of","although"],3,"Sonrasında isim grubu var: because of. Because / since / as tam cümle ister."),
("cause-noun","The company went bankrupt ____ it failed to adapt to changing markets.",["due to","owing to","because of","because","in spite of"],3,"Sonrasında tam cümle (it failed ...) var; due to / owing to / because of isim ister."),
("cause-noun","____ the generous scholarship, she was able to continue her studies abroad.",["Thanks to","Despite","Although","Unless","Whereas"],0,"Olumlu bir sonucun nedeni isimle verilmiş: Thanks to. Although / Whereas / Unless tam cümle ister."),
("cause-given","____ you have already paid for the ticket, you may as well use it.",["Now that","Unless","Even if","Whereas","Although"],0,"Gerçekleşmiş durumdan sonuç çıkarılıyor: Now that ('madem ki'). Unless ve Even if varsayım bildirir."),
("cause-given","____ the limited budget, the committee had to cut several projects.",["Given","Now that","Seeing that","Provided that","Although"],0,"Sonrasında isim grubu var: Given. Now that / Seeing that / Provided that tam cümle ister."),
("result-adv","The treatment is expensive; ____ few patients can afford it.",["therefore","because","although","despite","unless"],0,"Noktalı virgülden sonra sonuç bildiren zarf gerekir. Because / although bağlaçtır; despite isim ister."),
("result-adv","He had not prepared well for the interview. ____, he did not get the job.",["As a result","As a result of","Because","Due to","Since"],0,"'As a result' cümleler arası zarftır. 'As a result of' isim ister; because / due to / since neden bildirir, sonuç değil."),
("so-that-degree","The results were ____ surprising that the team repeated the experiment.",["so","such","very","too","quite"],0,"Sıfat (surprising) tek başına ve that ile sonuç cümlesi var: so ... that."),
("so-that-degree","There were ____ many applicants that the company had to extend the deadline.",["so","such","too","very","enough"],0,"so many / so much + isim + that. Such doğrudan many ile kullanılmaz."),
("such-that","It was ____ cold day that all the schools were closed.",["so","such a","such","so a","too"],1,"Tekil sayılabilir isim (day) önünde such a gerekir; 'so a' kalıbı yoktur."),
("such-that","They are ____ talented players that every club wants to sign them.",["so","such","such a","too","very"],1,"Çoğul isimde such kullanılır, a gelmez."),
("purpose-clause","She spoke slowly ____ everyone could understand her.",["in order to","so that","in spite of","because of","unless"],1,"Yeni özne (everyone) ve modal (could) var: so that. In order to özne değişmediğinde yalın fiille kullanılır."),
("purpose-clause","He told her the truth ____ she would not worry.",["so that","in order to","lest she","in order not","so as to"],0,"Hem özne (she) hem de modal (would) var: so that. Olumsuz amaç cümlesi 'so that ... not' ile de kurulabilir; lest ise 'she' için should / V1 ister."),
("purpose-inf","____ avoid delays, passengers are advised to arrive two hours early.",["In order to","So that","In order that","Because","Although"],0,"Sonrasında yalın fiil (avoid) var: In order to. So that / In order that yeni özne ister."),
("purpose-inf","This device is used ____ measuring air pressure.",["for","in order to","so as to","so that","lest"],0,"Aracın işlevi 'for + V-ing' ile anlatılır; in order to / so as to V-ing almaz."),
("lest","He spoke quietly lest he ____ the baby.",["wakes","would wake","wake","woke","will wake"],2,"Lest sonrasında yalın fiil (veya should + V1) gelir; zaman uyumu aranmaz."),
("lest","They locked the gates ____ intruders should enter.",["lest","unless","so that","in order to","although"],0,"Olumsuz amaç + should: lest. So that ile 'should enter' olumsuz anlam vermez."),
("in-case","We should save some money ____ an emergency.",["in case of","in case","if","unless","although"],0,"Sonrasında isim grubu var: in case of. In case tam cümle ister."),
("in-case","She wrote down the address ____ she should forget it.",["in case","in case of","despite","because of","as long as"],0,"Sonrasında tam cümle var ve önlem anlamı isteniyor: in case. In case of isim ister."),
("condition-strict","You can borrow my car ____ you return it by six.",["provided that","even if","in case","unless","although"],0,"'Şartıyla' anlamı: provided that. Unless ve even if anlamı bozar."),
("condition-strict","____ you finish your homework will you be allowed to play.",["Only if","Even if","Unless","Whether","Although"],0,"Cümle başında 'Only if' devrik yapı (will you ...) gerektirir."),
("unless","The company will not survive ____ it cuts costs.",["unless","if not","if","whether","although"],0,"'Maliyetleri kesmedikçe' anlamı: unless + olumlu fiil. 'If not' ile birlikte fiil de olumsuz olurdu."),
("unless","We will go for a picnic ____ it rains.",["unless","if","provided that","as long as","in case"],0,"'Yağmur yağmadıkça' anlamı: unless. If / provided that / as long as anlamı tersine çevirir."),
("even-if","____ he apologised sincerely, she refused to forgive him.",["Even though","Even if","Unless","Provided that","In case"],0,"Geçmişte gerçekleşmiş bir durum var: even though. Even if olasılık bildirir."),
("even-if","____ it rains tomorrow, we will still go hiking.",["Even if","Even though","Despite","Because","So that"],0,"Henüz gerçekleşmemiş bir olasılık var: even if. Even though gerçekleşmiş durum için kullanılır."),
("inverted-conditionals","____ I known about the problem, I would have helped.",["Have","Had","Would","Did","If"],1,"Ana cümlede would have helped (3. tip). If'siz devrik yapı: Had + özne + V3."),
("inverted-conditionals","____ you need any help, please do not hesitate to contact us.",["Should","Would","Had","Were","Did"],0,"Gelecek / olasılık anlamlı 1. tip koşulda devrik yapı: Should + özne + V1."),
("but-for","____ your advice, I would have made a terrible mistake.",["But for","Unless","Although","Because","While"],0,"Sonrasında isim var ve 'olmasaydı' anlamı isteniyor: But for. Unless / Although / Because / While tam cümle ister."),
("but-for","Had it not been ____ her support, the project would have failed.",["for","of","to","by","with"],0,"Kalıp: Had it not been for + isim."),
("otherwise","Please keep the receipt; ____ we cannot refund your money.",["otherwise","however","moreover","therefore","besides"],0,"Önceki cümlede istenen yapılmazsa olacak sonuç: otherwise."),
("otherwise","We must act quickly ____ we will lose the opportunity.",["or else","but","so that","although","since"],0,"'Yoksa' anlamı: or else. But zıtlık, so that amaç bildirir."),
("addition-adv","The hotel is cheap and clean; ____, it is close to the beach.",["moreover","however","nevertheless","consequently","instead"],0,"Aynı yönde ek bir olumlu bilgi var: moreover. However / nevertheless zıtlık bildirir."),
("addition-adv","The plan is practical. ____, it is cheaper than the alternatives.",["In addition","In addition to","Besides of","Because","Despite"],0,"Cümle arası ekleme zarfı: In addition. 'In addition to' isim ister; 'besides of' diye kalıp yoktur."),
("addition-noun","____ being intelligent, she is also very hardworking.",["Besides","Despite","Instead of","Unlike","In spite of"],0,"Sonrasında V-ing var ve anlam 'ek olarak': Besides. Despite / In spite of zıtlık, instead of tercih bildirir."),
("addition-noun","____ the fee, you must pay a deposit.",["In addition to","Moreover","Furthermore","However","Consequently"],0,"Sonrasında isim grubu var: In addition to. Moreover / Furthermore cümleler arası zarftır."),
("not-only","Not only ____ the exam, but he also won the top prize.",["he passed","did he pass","he did pass","passed he","does he pass"],1,"Not only cümle başındayken devrik yapı gerekir: Not only did he pass ..."),
("not-only","She is not only intelligent but also ____.",["hardworking","works hard","a hard working person","to work hard","working hard"],0,"Paralellik: sıfat (intelligent) ile sıfat (hardworking) eşleşir."),
("both-and","Both the teachers ____ the students were excited about the trip.",["and","or","nor","as well as","but"],0,"Both yalnızca and ile eşleşir."),
("both-and","The new phone is both fast ____ reliable.",["and","or","but","as","also"],0,"Both ... and; both ... or / both ... but yoktur."),
("either-neither","Neither Tom nor his parents ____ the news yet.",["has heard","have heard","hears","did heard","having heard"],1,"Neither ... nor yapısında fiil, nor'a yakın özneye uyar: his parents → have heard."),
("either-neither","He could not find the keys, and ____ could he find his wallet.",["neither","either","so","too","also"],0,"Olumsuz cümleden sonra devrik 'neither could he' kullanılır; either / so / too / also bu yapıyı kuramaz."),
("time-while","She was reading a book ____ the lights went out.",["when","while","during","as soon as","until"],0,"Past continuous eylem ve onu kesen kısa olay: 'when the lights went out'. While + kısa olay kullanılmaz; during isim ister."),
("time-while","____ the lecture, several students fell asleep.",["While","During","When","As","Although"],1,"Sonrasında isim grubu (the lecture) var: During. While / When / As tam cümle ister."),
("time-as-soon","I will call you as soon as I ____ home.",["will get","get","got","am getting","would get"],1,"Zaman bağlacından sonra gelecek için present simple kullanılır."),
("time-as-soon","____ the sun rose, the birds began to sing.",["The moment","During","Throughout","Despite","Prior to"],0,"Sonrasında tam cümle ve 'ir -mez' anlamı: The moment. During / Throughout / Despite / Prior to isim ister."),
("time-until","Don't open the box ____ I tell you to.",["until","by","during","since","while"],0,"Eylemin o ana kadar sürmemesi gerektiği anlatılıyor: until. By tek seferlik bitiş anlatır."),
("time-until","I will finish the report ____ Friday.",["until","by","by the time","while","since"],1,"Bitiş zamanı (en geç Cuma) için by kullanılır; until sürekliliği anlatır."),
("time-by-the-time","By the time we arrived, the film ____.",["started","had started","starts","has started","was starting"],1,"By the time + past simple → ana cümlede past perfect."),
("time-by-the-time","By the time she retires, she ____ here for forty years.",["works","worked","will have worked","is working","has worked"],2,"By the time + present simple → ana cümlede future perfect."),
("time-whenever","____ I visit my grandmother, she bakes a cake.",["Whenever","Wherever","Whatever","Whoever","However"],0,"Zaman anlamı ve tekrar eden durum: Whenever."),
("time-whenever","Call me ____ you need help.",["whenever","whatever","whoever","wherever","however"],0,"Zaman anlamlı genelleme: whenever."),
("time-since","I ____ him since 2015.",["don't see","didn't see","haven't seen","am not seeing","won't see"],2,"Since ile present perfect kullanılır."),
("time-since","It has been five years ____ we last met.",["since","for","ago","before","until"],0,"'It has been + süre + since + past simple' kalıbı."),
("time-hardly","Hardly had he sat down ____ the phone rang.",["when","than","that","as","while"],0,"Hardly ... WHEN; No sooner ... THAN."),
("time-hardly","No sooner had the film started ____ the power went out.",["than","when","that","then","as"],0,"No sooner ... THAN; Hardly ... WHEN."),
("time-before","____ signing the contract, read it carefully.",["Prior to","Prior","Previously","Until","After"],0,"Sonrasında V-ing var: Prior to + V-ing."),
("time-before","She had worked as a nurse ____ she became a doctor.",["before","prior to","previous to","ahead of","earlier"],0,"Sonrasında tam cümle var: before. Prior to / ahead of isim ister."),
("time-after","____ the speech, there was a long applause.",["Following","Next","Later","Then","Afterwards"],0,"Sonrasında isim var: Following. Next / later / then / afterwards zarftır."),
("time-after","____ completing the course, students receive a certificate.",["Upon","Upon to","After to","Following to","While to"],0,"Upon + V-ing kalıbı."),
("time-during","He fell asleep ____ the film.",["during","while","for","since","when"],0,"Sonrasında isim (the film) var: during. While / when tam cümle ister."),
("time-during","She worked abroad ____ three years.",["for","during","while","since","throughout"],0,"Süre miktarı için for kullanılır."),
("instead-of","Why don't you walk ____ taking the bus?",["instead of","instead","rather","in place","besides"],0,"Sonrasında V-ing var: instead of. Instead tek başına zarftır."),
("instead-of","I would rather stay home ____ go out in this weather.",["than","to","of","instead","from"],0,"Would rather + V1 + than + V1."),
("except","Everyone ____ Mark attended the meeting.",["except","besides","apart","unless","beyond"],0,"'Mark hariç' anlamı: except."),
("except","The shop is open every day ____ Sundays.",["except","instead of","unless","without","until"],0,"'Pazar günleri hariç' anlamı: except."),
("whatever-however","____ happens, I will support you.",["Whatever","However","Whenever","Wherever","Whichever"],0,"'Ne olursa olsun' anlamı: whatever."),
("whatever-however","____ hard she tries, she cannot win.",["However","Whatever","Whoever","Whenever","Wherever"],0,"However + sıfat / zarf + özne + fiil."),
("whether","I wonder ____ she will accept the offer.",["whether","unless","although","whereas","in case"],0,"Dolaylı soru: whether."),
("whether","The decision depends on ____ the funding is approved.",["whether","if","unless","that","what"],0,"Edattan sonra if değil whether kullanılır."),
("as-if","He behaves as if he ____ the boss, but he is just an intern.",["is","were","will be","has been","being"],1,"Gerçek dışı durumda as if + were."),
("as-if","It looks ____ it is going to rain.",["as if","as","such as","despite","unless"],0,"Benzetme: as if + cümle."),
("according-to","____ me, this plan is too risky.",["In my opinion","According to","Based","Following","Owing to"],0,"According to kişinin kendi görüşünde kullanılmaz; In my opinion denir."),
("according-to","The work was done ____ the instructions.",["in accordance with","according","because","owing","regarding"],0,"Kurala uygunluk: in accordance with."),
("regarding","____ your question, I will reply tomorrow.",["With regard to","Because of","Unlike","Despite","Although"],0,"Konuyu belirtir: With regard to."),
("regarding","I am writing with ____ to your recent application.",["regard","regards","regarding","respecting","regarded"],0,"Kalıp: with regard to (regard tekil)."),
("similarly","The first speaker supported the plan; ____, the second one expressed her approval.",["similarly","however","otherwise","on the other hand","instead"],0,"İki cümle aynı yönde: similarly."),
("similarly","He enjoys cooking. ____, his wife loves baking.",["Likewise","Nevertheless","Otherwise","Whereas","Despite"],0,"Benzer durum: likewise."),
("for-example","Many animals, ____ elephants and whales, are endangered.",["such as","such","as such","for example of","like as"],0,"İsim grubu listesi için such as kullanılır."),
("for-example","Some fruits are rich in vitamin C. ____, oranges and kiwis.",["For example","Therefore","However","Otherwise","Despite"],0,"Örnek veren cümle arası ifade: For example."),
("in-other-words","He is a vegetarian; ____, he doesn't eat meat.",["in other words","on the other hand","as a result","by contrast","instead"],0,"İkinci cümle birincinin yeniden ifadesi: in other words."),
("in-other-words","The company has gone bankrupt; ____, it can no longer pay its debts.",["in other words","on the contrary","nevertheless","likewise","for instance"],0,"İkinci cümle birinciyi açıklıyor: in other words."),
("in-conclusion","____, we can say that the project was a success.",["In conclusion","In contrast","In addition","Instead","However"],0,"Genel sonuç: In conclusion."),
("in-conclusion","He was late, he forgot his notes, and he was nervous. ____, the presentation was a disaster.",["All in all","On the other hand","Moreover","Whereas","Unless"],0,"Özetleyen sonuç: All in all."),
("in-fact","People think he is rich. ____, he has huge debts.",["In fact","In case","In order","In spite","In addition"],0,"Yanlış varsayımı düzeltir: In fact."),
("in-fact","The task was not difficult; ____, it was surprisingly easy.",["in fact","unless","whereas","lest","provided"],0,"Önceki ifadeyi güçlendirir: in fact."),
("meanwhile","Ann was cooking dinner. ____, Tom was setting the table.",["Meanwhile","Moreover","Instead","Otherwise","Besides"],0,"Aynı anda gerçekleşen olay: Meanwhile."),
("meanwhile","The results will be announced next week. ____, please be patient.",["In the meantime","In contrast","In case","In addition","In fact"],0,"Beklenen süre boyunca: In the meantime."),
("afterwards","We had dinner, and ____ we went for a walk.",["afterwards","after","before","during","while"],0,"Zarf olarak 'sonrasında' anlamı: afterwards."),
("afterwards","The patient was given medicine; ____, his fever dropped.",["subsequently","previously","in contrast","however","unless"],0,"Kronolojik sıra: subsequently."),
("result-so","It was raining heavily, ____ we stayed at home.",["so","because","although","unless","whereas"],0,"Virgülden sonra sonuç bildiren bağlaç: so."),
("result-so","He studied hard, ____ he passed the exam.",["so","because","but","although","whereas"],0,"Sonuç bildirir: so. But / although zıtlık bildirir."),
("as-a-result-of","____ the strike, all flights were cancelled.",["As a result of","As a result","Therefore","Consequently","Because"],0,"Sonrasında isim var: As a result of."),
("as-a-result-of","The factory closed down. ____, hundreds of people lost their jobs.",["As a result","As a result of","Due to","Because of","Despite"],0,"Cümleler arası zarf: As a result."),
("by-means-of","They crossed the river ____ a rope bridge.",["by means of","owing to","in spite of","instead","because"],0,"Araç belirten isim grubu: by means of."),
("by-means-of","The message was transmitted ____ a satellite.",["by means of","because of","thanks","despite","unlike"],0,"Araç / vasıta: by means of."),
("but","He tried hard, ____ he failed.",["but","although","because","so","unless"],0,"Virgülden sonra zıtlık: but. Although ile ikinci yarı bağlanamaz."),
("but","____ she was tired, she kept working.",["Although","But","Yet","However","Therefore"],0,"Cümle başında yan cümle başlatan bağlaç: Although. But / yet / however cümleyi başlatamaz."),
("regardless-of","Everyone is welcome, ____ age or background.",["regardless of","regardless","regarding","despite of","instead"],0,"Sonrasında isim var: regardless of."),
("regardless-of","The law applies to all citizens ____ they are rich or poor.",["regardless of whether","regardless","despite","although","in spite"],0,"Sonrasında whether cümlesi var: regardless of whether."),
("as-as","She is as tall ____ her brother.",["as","than","like","that","so"],0,"Eşitlik kalıbı: as ... as."),
("as-as","There aren't ____ students in this class as in the other one.",["as many","as much","so much","more","such"],0,"Sayılabilir isim (students): as many ... as."),
("just-as","Just as the sun rises in the east, ____ it sets in the west.",["so","however","although","unless","because"],0,"Just as ... so kalıbı."),
("just-as","He treated her ____ he would treat his own sister.",["just as","such as","unlike","despite","whereas"],0,"Benzetme: just as + cümle."),
("if-basic","If it ____ tomorrow, we will cancel the picnic.",["rains","will rain","would rain","rained","had rained"],0,"If cümlesinde will / would kullanılmaz; ana cümlede will var: present simple."),
("if-basic","If I ____ you, I would accept the offer.",["am","were","would be","will be","have been"],1,"2. tip koşul: If + were, would + V1."),
("time-upon","____ the news, she burst into tears.",["Upon hearing","Upon heard","Upon hear","Upon to hear","Upon being hear"],0,"Upon + V-ing."),
("time-upon","____ arrival, the guests were shown to their rooms.",["Upon","During","Until","Since","Although"],0,"Upon arrival kalıbı."),
("in-terms-of","The two cities are similar ____ size but different in climate.",["in terms of","because of","despite","according","owing"],0,"Açısından: in terms of."),
("in-terms-of","____ salary, the job is excellent.",["In terms of","As a result","Because","Although","Whereas"],0,"Sonrasında isim var ve 'açısından': In terms of."),
("along-with","The manager, along with his assistants, ____ attending the conference.",["are","is","were","have","being"],1,"Along with araya girse de özne tekildir (the manager)."),
("along-with","Mary, together with her sisters, ____ visiting us tomorrow.",["is","are","were","have been","be"],0,"Together with araya girse de özne tekildir (Mary)."),
("by-ving","You can improve your English ____ a lot.",["by reading","by read","for reading","to reading","with read"],0,"By + V-ing: yöntem."),
("by-ving","He saved money ____ walking to work instead of driving.",["by","to","for","with","in order"],0,"Yöntem: by + V-ing."),
("instead-adv","I didn't go to the party. ____, I stayed home and read.",["Instead","Instead of","Rather than","In place of","Unlike"],0,"Cümle başında tek başına: Instead."),
("instead-adv","Don't waste money on sweets. Buy fruit ____.",["instead","instead of","in spite of","unlike","such as"],0,"Cümle sonunda tek başına: instead."),
]
cards = {c["id"] for c in json.load(open("data/conjunctions.json", encoding="utf-8"))}
out = []
for i, (cid, stem, opts, ans, trap) in enumerate(T, 1):
    assert cid in cards, cid
    assert len(opts) == 5 and 0 <= ans < 5, stem
    out.append({"id": f"t{i:03d}", "cardIds": [cid], "kind": "trap", "stem": stem, "options": opts, "answer": ans,
                "explanation": f"Doğru cevap: {opts[ans]}. Tuzak: {trap}"})
json.dump(out, open("data/questions-trap.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)
per = {}
for q in out: per[q["cardIds"][0]] = per.get(q["cardIds"][0], 0) + 1
print(len(out), "tuzak sorusu;", "kartlar:", len(per), "eksik:", sorted(cards - set(per)))
